config/routes.rb
Rails.application.routes.draw do
  # resources :likes
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :tweets do
    resources :likes
  end
  get '/api/news' => 'api#news'
  resources :api do 
    resources :news
  end

  post '/api', action: :new_tweet, controller: 'api'

  get '/api/:fecha1/:fecha2' => 'api#date'

  root 'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    has_many :likes
    belongs_to :user
    scope :created_at, -> (first, last) { where('created_at >= ? AND created_at <=?', first, last) }
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.order('created_at DESC').page(params[:page]).per(50)
    @tweet = Tweet.new
  
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path , notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { root_path :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :user_id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'form', tweet: @tweet %>

<div class="row">
  <div class="col-xs-8 col-sm-10 col-md-10">
    <h1>Tweets</h1>
  </div>
  <div class="col-xs-4 col-sm-2 col-md-2">
    <%= link_to 'New Tweet', new_tweet_path, class: "btn-outline-secondary btn-sm" %>
  </div>
</div>

<div class="row">
  <% @tweets.each do |tweet| %>
  <div class="col-sm-6 col-md-4">
    <%= image_tag tweet.user.image_url %>
    <%= link_to 'Like',tweet_likes_path(tweet), method: :post%>
      <div class="thumbnail">
        <div class="caption">
          <p><%= tweet.content.truncate(150) %></p>
          <p><%= link_to 'Show', tweet, class: "btn btn-outline-primary" %> 
            <% if current_user&.id == tweet.user_id %>
              <%= link_to 'Edit', edit_tweet_path(tweet), class: "btn btn-outline-info" %> 
              <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %></p>     
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>


<br>




<%= link_to_next_page @tweets, 'Mostrar mas tweets' %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @tweet.content %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @tweet.user.image_url %>
</p>

<p>
  <strong>Likes cuantity:</strong>
  <%= link_to "Like", tweet_like_path(@tweet), method: :put, remote: :true %>
</p>



<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>