config/routes.rb
Rails.application.routes.draw do
  # resources :likes
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :tweets do
    resources :likes
  end
  get '/api/news' => 'api#news'
  resources :api do 
    resources :news
  end

  post '/api', action: :new_tweet, controller: 'api'

  get '/api/:fecha1/:fecha2' => 'api#date'

  root 'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Felipe Letelier</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Perfil
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if current_user %>
              <p><%=link_to 'Create new Tweet', new_tweet_path %></p>
              <p><%=link_to 'My Tweets', tweet_path(current_user) %></p>
              <p><%=link_to 'My Profile', edit_user_registration_path %></p>
              <p role="separator" class="divider"></p>
              <p><%=link_to 'Log Out', destroy_user_session_path, method: :delete %></p>
          <% else %>
              <p><%=link_to 'Sign In', new_user_session_path %></p>
              <p><%=link_to 'Sign Up', new_user_registration_path %></p>
          <% end %>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>